### ISSUE TITLE
Fix: GitHub Actions workflow failing with npm eslint property error

### ISSUE THREAD

**Issue by eshanjain** [eshanjain/workflow-project#1]
## Root Cause
The workflow is failing due to a corrupted or malformed package-lock.json file. The error "Cannot read property 'eslint' of undefined" suggests that npm is trying to access an 'eslint' property on an object that is undefined. This typically happens when the package-lock.json file contains invalid or corrupted references. The error occurs specifically during the `npm ci` command, which strictly uses the package-lock.json file for installation.

## Mitigation Steps
1. Update Node.js version from 14.x to 16.x in the workflow file for better compatibility with modern dependencies
2. Replace the `npm ci` command with a process that:
   - Removes the existing package-lock.json file
   - Runs `npm install` to generate a fresh package-lock.json based on the package.json

The updated workflow step should look like:
```yaml
- uses: actions/checkout@v2
- name: Use Node.js
  uses: actions/setup-node@v2
  with:
    node-version: '16.x'
- name: Clean install with package-lock regeneration
  run: |
    rm -f package-lock.json
    npm install
```

## PR Link
No PR created

## Validation Results
**Status:** Failed
