### ISSUE TITLE
Fix npm ci error in GitHub Actions workflow

### ISSUE THREAD

**Issue by eshanjain** [eshanjain/workflow-project#2]
## Root Cause
The package-lock.json file contains a deprecated package reference that's causing npm to fail during installation. The error message 'Cannot read property 'eslint' of undefined' indicates that npm is trying to access an eslint property on an undefined object during the installation process. In the package-lock.json file, there are two deprecated packages: '@humanwhocodes/config-array' and '@humanwhocodes/object-schema' which are dependencies of eslint, and the error occurs specifically when npm tries to process these dependencies during installation.

## Mitigation Steps
1. Regenerate the package-lock.json file:
```bash
rm package-lock.json
npm install
```

2. Update GitHub Actions to use the latest versions:
   - Update actions/checkout from v2 to v4
   - Update actions/setup-node from v2 to v4

The updated workflow file should look like:
```yaml
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run lint
```

## PR Link
No PR created

## Validation Results
**Status:** Failed
