### ISSUE TITLE
Fix: GitHub Actions workflow failure in npm ci step

### ISSUE THREAD

**Issue by eshanjain** [eshanjain/workflow-project#4]
## Root Cause
The workflow was failing with the error "Cannot read property 'eslint' of undefined" during the npm ci step. This was caused by a dependency conflict in npm package resolution, specifically with ESLint-related dependencies. The package-lock.json file contained multiple deprecated dependencies, and Node.js 14.x might not be fully compatible with the latest versions of these dependencies.

## Mitigation Steps
1. Update the Node.js version in the GitHub Actions workflow:
   ```yaml
   - name: Use Node.js
     uses: actions/setup-node@v2
     with:
       node-version: '16.x'  # Updated from '14.x'
   ```

2. Regenerate the package-lock.json file:
   ```bash
   rm package-lock.json
   npm install
   ```

These changes ensure better compatibility between Node.js and the project dependencies, particularly ESLint-related packages, and resolve the dependency conflicts that were causing the npm ci command to fail.

## PR Link
No PR created

## Validation Results
**Status:** Failed
